const express = require("express");
const router = express.Router();

const { GoogleSpreadsheet } = require('google-spreadsheet');

// Initialize the sheet - doc ID is the long id in the sheets URL
const doc = new GoogleSpreadsheet('1D4L3yz-2lkjO76SIRZ8xKfKniigvttobtDzzwD0ZaM8');

async function getEvents(year) {
    // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
    await doc.useServiceAccountAuth({
        // env var values are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        client_email: 'ecell-service-acc@ecell-project-381520.iam.gserviceaccount.com',
        private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkBGuHUj8SNFkV\nWDOc4ewgDVAHWA/fgCxFGXZp7Nr79rOC76vRYbB8sg8Htb0ol8RKq+oyHerYIHE8\njMKE6OZCe4eb3yarR6cTcxkXZUxo8Mo1wMbR8HI2ybTW6aGVrAFmWJQeaaVZDvby\nBCYIHIeM7+gWsPmJWEdQkdPAfwkaR7v4rA6SOFzZu7mNzfF0/S1GbGs545Y0ccMG\nzhy80xmkDYvJOUr9FajbRacvWgXp3kejy0w/T72zw/6YqH1G+vv/tjsbqbS9h765\nLdbfLxPGdLxMcCCanGBCcMtyUJiMcUKlkYcLDAr5uyu3jNBXx+LnIGtiSpnKrezb\n0YqXH2eLAgMBAAECggEAG8tr9Xiom4sndYiG5pUakKvw3e28cuGjnuobuQOccIp0\nDUJUWZ02bUs3ZNUVgyWE7CqJ+4g6XfnRdrNb224kZyvL5UxBn1D7LT6aB+7wre/w\nNH/AsZ8Pm90+uhTJfzWw3wkvwJ+il58DlivBzioXhni5We8PuoitPSgZPEvK3Rr5\nbEhPc87tZO03PygcHgnkqBeCqUFmXXF1ZzyfuTZDLSGOBbimqUmKgnevUocxGXIF\nBUwjNH6M+gIPRMbFVW+U4/OZtC2fQnXTV+n2FuBsQ0aDM4BlMzHWRobbN1REaui+\nSWGP+GWsMIUESAvBXzAUGM0gdmZUX/58MmnISkzAMQKBgQDVSKEAbJ2fynM/Wr9K\nr0h9J8awBj1eRuBAbNGHzhr5DwHENnG9zbFTLMfO+z94z+4VWiw9TH/YfpZMsHBi\nw0sT6lLtCjwkx+hjQuqqBvp/bxOARTw8jZoGU3G7VlM5xn/ZsyzTsrg2+Z67JrEB\nupSq44pj7SyDFzTji92voxy7PwKBgQDE3dPsoOqaq+vDibI8Op5EShIk2RrozISV\nEnLPKX+k8+fLRzQ/1CcpvzjKLxEb6H3yaDSw+ssRIRm/8t4cicBbcITISZhD2C9V\n+19jl+2yFWQgvGPGGDAYjb4oiegrY6yxC9g+wYnkLXJmZisFurevHobsxpswgqG9\nRU28hkP8tQKBgEqJGjLiwmcQQhxW41j/Tq7mUqo7VAD5de8t2D/EiGqXkv92I2O4\nWYr+sEkmRrU6vTJbE/DMJjWLb40Xb/8jzr4D+rz6AbC85/qgbQ/EZpBYShFeoMFs\nnvItASb98RHUy+NRmY3V/EjCDXXL/Lnk8YWTBU8MmKyrVIFc5Lk3oJfTAoGBALQT\n5cLR/0e0c1jOH8eQJy14Q9iI72B7k9t4oKR25VfR8/myDE1GlvxM+nmXTCMnK+4M\n/AXXouDsUk2OrzWTm+0Io61CBJIqskIISl0joD4B6zE2ol2VyojrP0J9w23NIy5g\nE1J0Xtnl6HtagYggH92EIw97LIHXPHORbWZBuvbxAoGAWjEb0swDF/WLnEn0EDRA\n1QmsLn29wp0BFCC/Z3hjunNruRfWT6sS3O+gkwG9fia4w+BGkto1rzopYQt8l1LR\nC8dyT9Ni/Yb6SLktnkyddJyXwbJItr6vG8oh7+BaCWJlxgBYw48A6iiiaDJcGBcl\n2ODEsuPajnfdnSXAvt2MfYE=\n-----END PRIVATE KEY-----\n",
    });

    await doc.loadInfo(); // loads document properties and worksheets
    const sheet = doc.sheetsByTitle[year]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
    const rows = await sheet.getRows();
    return rows;
}

async function getStartups() {
    // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
    await doc.useServiceAccountAuth({
        // env var values are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        client_email: 'ecell-service-acc@ecell-project-381520.iam.gserviceaccount.com',
        private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkBGuHUj8SNFkV\nWDOc4ewgDVAHWA/fgCxFGXZp7Nr79rOC76vRYbB8sg8Htb0ol8RKq+oyHerYIHE8\njMKE6OZCe4eb3yarR6cTcxkXZUxo8Mo1wMbR8HI2ybTW6aGVrAFmWJQeaaVZDvby\nBCYIHIeM7+gWsPmJWEdQkdPAfwkaR7v4rA6SOFzZu7mNzfF0/S1GbGs545Y0ccMG\nzhy80xmkDYvJOUr9FajbRacvWgXp3kejy0w/T72zw/6YqH1G+vv/tjsbqbS9h765\nLdbfLxPGdLxMcCCanGBCcMtyUJiMcUKlkYcLDAr5uyu3jNBXx+LnIGtiSpnKrezb\n0YqXH2eLAgMBAAECggEAG8tr9Xiom4sndYiG5pUakKvw3e28cuGjnuobuQOccIp0\nDUJUWZ02bUs3ZNUVgyWE7CqJ+4g6XfnRdrNb224kZyvL5UxBn1D7LT6aB+7wre/w\nNH/AsZ8Pm90+uhTJfzWw3wkvwJ+il58DlivBzioXhni5We8PuoitPSgZPEvK3Rr5\nbEhPc87tZO03PygcHgnkqBeCqUFmXXF1ZzyfuTZDLSGOBbimqUmKgnevUocxGXIF\nBUwjNH6M+gIPRMbFVW+U4/OZtC2fQnXTV+n2FuBsQ0aDM4BlMzHWRobbN1REaui+\nSWGP+GWsMIUESAvBXzAUGM0gdmZUX/58MmnISkzAMQKBgQDVSKEAbJ2fynM/Wr9K\nr0h9J8awBj1eRuBAbNGHzhr5DwHENnG9zbFTLMfO+z94z+4VWiw9TH/YfpZMsHBi\nw0sT6lLtCjwkx+hjQuqqBvp/bxOARTw8jZoGU3G7VlM5xn/ZsyzTsrg2+Z67JrEB\nupSq44pj7SyDFzTji92voxy7PwKBgQDE3dPsoOqaq+vDibI8Op5EShIk2RrozISV\nEnLPKX+k8+fLRzQ/1CcpvzjKLxEb6H3yaDSw+ssRIRm/8t4cicBbcITISZhD2C9V\n+19jl+2yFWQgvGPGGDAYjb4oiegrY6yxC9g+wYnkLXJmZisFurevHobsxpswgqG9\nRU28hkP8tQKBgEqJGjLiwmcQQhxW41j/Tq7mUqo7VAD5de8t2D/EiGqXkv92I2O4\nWYr+sEkmRrU6vTJbE/DMJjWLb40Xb/8jzr4D+rz6AbC85/qgbQ/EZpBYShFeoMFs\nnvItASb98RHUy+NRmY3V/EjCDXXL/Lnk8YWTBU8MmKyrVIFc5Lk3oJfTAoGBALQT\n5cLR/0e0c1jOH8eQJy14Q9iI72B7k9t4oKR25VfR8/myDE1GlvxM+nmXTCMnK+4M\n/AXXouDsUk2OrzWTm+0Io61CBJIqskIISl0joD4B6zE2ol2VyojrP0J9w23NIy5g\nE1J0Xtnl6HtagYggH92EIw97LIHXPHORbWZBuvbxAoGAWjEb0swDF/WLnEn0EDRA\n1QmsLn29wp0BFCC/Z3hjunNruRfWT6sS3O+gkwG9fia4w+BGkto1rzopYQt8l1LR\nC8dyT9Ni/Yb6SLktnkyddJyXwbJItr6vG8oh7+BaCWJlxgBYw48A6iiiaDJcGBcl\n2ODEsuPajnfdnSXAvt2MfYE=\n-----END PRIVATE KEY-----\n",
    });

    await doc.loadInfo(); // loads document properties and worksheets
    const sheet = doc.sheetsByTitle['JU Startup List']; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
    const rows = await sheet.getRows();
    return rows;
}

// index page
router.get("/", function (req, res) {
    res.render("pages/index", {});
});

// about page
router.get("/about", function (req, res) {
    res.render("pages/about", {});
});

// startups page
router.get("/startups", async function (req, res) {
    let startupList = await getStartups();
    res.render("pages/startups", { startups: startupList });
});

// events page
router.get("/events", async function (req, res) {
    let years = ['2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016'];
    let events = {};
    events['2023'] = await getEvents('2023');
    // console.log(events);
    // console.log(events.length);
    res.render("pages/events", { eventList: events });
});

// contact page
router.get("/contact", function (req, res) {
    res.render("pages/contact", {});
});

// hult page
router.get("/hult", function (req, res) {
    res.render("pages/hult", {});
});

// eweekend page
router.get("/eweekend", function (req, res) {
    res.render("pages/eweekend", {});
});

// esummit page
router.get("/esummit", function (req, res) {
    res.render("pages/esummit", {});
});
// initiatives page
router.get("/initiatives", function (req, res) {
    res.render("pages/initiatives", {});
});

// join-us page
router.get("/join-us", function (req, res) {
    res.render("pages/join-us", {});
});

// tinkering-lab page
router.get("/tinkering-lab", function (req, res) {
    res.render("pages/tinkering-lab", {});
});


module.exports = router;